version: "3.8"

services:
  frontend:
    build: ../client
    container_name: potbath_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./
    container_name: potbath_backend
    command: bash -c "npx prisma migrate dev && npx prisma db seed && npm run dev"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 32050832
      POSTGRES_HOST: db
      POSTGRES_PORT: 5436
      POSTGRES_DATABASE: potbath
      JWT_SECRET: top_secret
      DATABASE_URL: postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: potbath_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 32050832
      POSTGRES_DB: potbath
    command: postgres -p ${POSTGRES_PORT}
    ports:
      - "5436:5436"

  nginx:
    image: nginx
    container_name: potbath_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

